name = "recap-backend"
main = "src/index.js"
compatibility_date = "2024-09-25"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "recap-db"
database_id = "2a479ac4-3e27-4df9-a33b-c921c753fd88"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "recap-index"
